hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.student.StudentCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.student.StudentDayCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.student.StudentMonthCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.classCS.ClassCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.classCS.ClassDayCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.classCS.ClassMonthCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.major.MajorCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.major.MajorDayCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.major.MajorMonthCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.college.CollegeCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.college.CollegeDayCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.college.CollegeMonthCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.studentStore.StudentStoreCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.studentStore.StudentStoreDayCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.studentStore.StudentStoreMonthCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.store.StoreCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.store.StoreDayCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.store.StoreMonthCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.student.StudentTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.student.StudentDayTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.student.StudentMonthTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.classCS.ClassTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.classCS.ClassDayTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.classCS.ClassMonthTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.major.MajorTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.major.MajorDayTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.major.MajorMonthTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.college.CollegeTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.college.CollegeDayTCSStatisticsToDB
hadoop jar ./Analysis-1.0-SNAPSHOT.jar edu.run.college.CollegeMonthTCSStatisticsToDB
hadoop jar Analysis-1.0-SNAPSHOT.jar edu.run.mealsTime.MealsTimeCountStatisticsToDB
